eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: Rhng+FOlTEne/3lMQrmNh5samiSChUD8yOychVwC7EfmrlsMy3Te1bTjuspR2P2T
  access-expiry: 3600
  refresh-expiry: 86400